language: python
python:
  - "2.7"
# command to install dependencies, e.g. 
install: 
  - pip install .
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script: coverage run --source=mesan_compositer setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: adybbroe
  password:
    secure: FznD38SHxuj1RoFXUqLstF//O3+pypF84hCOHO8A3Poa+ygh7X4a+9aimCeiuY9d+5tbE0ZlyG7LMcCOFA3JCvH7lUChmQbbn3pcFvJdJzzYQgxYNfvCL9YtjRF/n648bVdpN265hm07rmOe7DHbysw4q8hMlxtUH87MYctRg90=
  on:
    tags: true
    repo: adybbroe/mesan_compositer
    branch: master
