[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "mesan_compositer"
dynamic = ["version"]
description = "Mesan satellite compositer"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPLv3"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering"
]
dependencies = [
    "satpy",
]


[project.optional-dependencies]
test = ["mock", "pytest"]
netcdf4-python = ["netCDF4"]


[project.urls]
Homepage = "https://github.com/adybbroe/mesan_compositer"


[project.scripts]
make_ct_composite = "mesan_compositer.make_ct_composite:main"
make_ctth_composite = "mesan_compositer.make_ctth_composite:main"
prt_nwcsaf_cloudamount = "mesan_compositer.prt_nwcsaf_cloudamount:main"
prt_nwcsaf_cloudheight = "mesan_compositer.prt_nwcsaf_cloudheight:main"
ct_quicklooks = "mesan_compositer.ct_quicklooks:main"
ctth_quicklooks = "mesan_compositer.ctth_quicklooks:main"
mesan_composite_runner = "mesan_compositer.mesan_composite_runner:main"
load_cloud_products = "mesan_compositer.load_cloud_products:main"


[tool.hatch.metadata]
allow-direct-references = true


[tool.hatch.version]
source = "vcs"


[tool.hatch.build.hooks.vcs]
version-file = "mesan_compositer/version.py"


[tool.hatch.build.targets.wheel]
packages = ["mesan_compositer"]

[tool.ruff]
lint.select = ["E", "W", "F", "I", "D", "S", "B", "A", "PT", "Q", "TID"]
lint.ignore = ["B905"]  # only available from python 3.10
line-length = 120

[tool.hatch.build.targets.sdist]
include = [
    "/mesan_compositer",
    "/README.md",
    "/LICENSE",
    "/pyproject.toml",
]
